// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVF5yWZ3Dfo6DN5v_FPpq6iqfIGlckbic',
    appId: '1:264301190550:web:87f22e7354d14972f751b7',
    messagingSenderId: '264301190550',
    projectId: 'focusly-9ac6a',
    authDomain: 'focusly-9ac6a.firebaseapp.com',
    storageBucket: 'focusly-9ac6a.firebasestorage.app',
    measurementId: 'G-T3ZDYLDWW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkz9nF_Iby0_jawCJBXMqbZN28lGDdjaQ',
    appId: '1:264301190550:android:6293e9b7847256a6f751b7',
    messagingSenderId: '264301190550',
    projectId: 'focusly-9ac6a',
    storageBucket: 'focusly-9ac6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_rzRZSu4KVQAeMDLkRWwVB5u_5DZ0wGs',
    appId: '1:264301190550:ios:aa8ddd987da809d4f751b7',
    messagingSenderId: '264301190550',
    projectId: 'focusly-9ac6a',
    storageBucket: 'focusly-9ac6a.firebasestorage.app',
    iosBundleId: 'com.example.focusly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_rzRZSu4KVQAeMDLkRWwVB5u_5DZ0wGs',
    appId: '1:264301190550:ios:aa8ddd987da809d4f751b7',
    messagingSenderId: '264301190550',
    projectId: 'focusly-9ac6a',
    storageBucket: 'focusly-9ac6a.firebasestorage.app',
    iosBundleId: 'com.example.focusly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVF5yWZ3Dfo6DN5v_FPpq6iqfIGlckbic',
    appId: '1:264301190550:web:be38858b71cc1662f751b7',
    messagingSenderId: '264301190550',
    projectId: 'focusly-9ac6a',
    authDomain: 'focusly-9ac6a.firebaseapp.com',
    storageBucket: 'focusly-9ac6a.firebasestorage.app',
    measurementId: 'G-HZ8HTHD5Q0',
  );
}
